services:
  postgres:
    image: 'postgres:17.2'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    networks:
      - rcrmNetwork
    volumes:
      - rcrmDbDev:/var/lib/rcrmDbDev

  redis:
    image: 'redis:7.4.1'
    container_name: my-redis-docker-service
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 20s
      retries: 3
    ports:
      - '6379:6379'
    expose:
      - '6379'
    networks:
      - rcrmNetwork
    command: ["redis-server"]
    volumes:
      - redisData:/data

networks:
  rcrmNetwork:
    driver: bridge

volumes:
  rcrmDbDev:
    driver: local
  redisData:
    driver: local
