services:
  postgres:
    image: 'postgres:17.2'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    networks:
      - rcrmNetwork
    volumes:
      - rcrmDbDev:/var/lib/rcrmDbDev

networks:
  rcrmNetwork:
volumes:
  rcrmDbDev:
    driver: local
